/**
 * Schema for `media.db` — media metadata + transfer state.
 *
 * Stores media job state (uploads/downloads with reupload retry tracking),
 * Express Path download cache, draft voice notes, recent searches, and
 * cross-session shared media identifiers. Column names match the canonical
 * mobile schema verbatim.
 */
export declare const MEDIA_SCHEMA = "\nCREATE TABLE IF NOT EXISTS android_metadata (locale TEXT);\n\nCREATE TABLE IF NOT EXISTS draft_voice_note_metadata (\n  chat_jid TEXT PRIMARY KEY NOT NULL,\n  page_number INTEGER\n);\n\nCREATE TABLE IF NOT EXISTS express_path_download_data (\n  enc_file_hash TEXT PRIMARY KEY NOT NULL,\n  ep_saved_time_ms INTEGER,\n  ep_saved_bytes INTEGER,\n  download_state INTEGER,\n  last_update_time INTEGER,\n  enc_file_restored INTEGER DEFAULT 0\n);\n\nCREATE INDEX IF NOT EXISTS enc_file_hash_index\n  ON express_path_download_data (enc_file_hash);\n\nCREATE TABLE IF NOT EXISTS media_job (\n  _id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,\n  uuid TEXT NOT NULL DEFAULT '',\n  job_type INTEGER,\n  create_time INTEGER,\n  transfer_start_time INTEGER,\n  last_update_time INTEGER,\n  user_initiated_attempt_count INTEGER,\n  overall_cumulative_time INTEGER,\n  overall_cumulative_user_visible_time INTEGER,\n  streaming_playback_count INTEGER,\n  media_key_reuse_type INTEGER,\n  doodle_id TEXT,\n  transferred_bytes INTEGER,\n  reupload_attempt_count INTEGER,\n  last_reupload_attempt_timestamp INTEGER,\n  last_reupload_success_timestamp INTEGER\n);\n\nCREATE TABLE IF NOT EXISTS recent_searches (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  search_query TEXT NOT NULL DEFAULT '',\n  search_entry_point TEXT NOT NULL DEFAULT '',\n  timestamp INTEGER NOT NULL DEFAULT 0,\n  UNIQUE(search_query, search_entry_point)\n);\n\nCREATE INDEX IF NOT EXISTS idx_recent_searches_search_entry_point\n  ON recent_searches (search_entry_point);\nCREATE INDEX IF NOT EXISTS idx_recent_searches_timestamp\n  ON recent_searches (timestamp DESC);\n\nCREATE TABLE IF NOT EXISTS shared_media_ids (\n  item_uuid TEXT PRIMARY KEY NOT NULL,\n  file_name TEXT NOT NULL DEFAULT '',\n  mime_type TEXT NOT NULL DEFAULT '',\n  display_name TEXT,\n  expiration_timestamp INTEGER NOT NULL DEFAULT 0\n);\n";
//# sourceMappingURL=media.d.ts.map